CALIBRATECODEGENDIR = /mnt/hgfs/jonathanbeard/GIT_RPO/ScheduleVariance/Calibrate/
CALIBRATECPPCODEBASE = \
   threethousand \
   hundred \
   twothousand \
   fourhundred \
   twohundred \
   fourty \
   sixty \
   eighty \
   thousand \
   fifty \
   fourthousand \
   seventy \
   twenty \
   fivethousand \
   ninety \
   threehundred \
   thirty \
   ten \
   twentythousand \
   tenthousand \
   fivehundred 

CALIBRATECPPCODE = $(addprefix $(CALIBRATECODEGENDIR), $(CALIBRATECPPCODEBASE))
